services:
  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    image: zebrand-backend_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
